global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "dockstat-dev"
    metrics_path: "/api/metrics"
    scheme: http
    static_configs:
      - targets: ["localhost:5173"]
