blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/Its4Nik/DockStat/discussions
    about: Ask questions and discuss ideas with the community
  - name: ğŸ“š Documentation
    url: https://dockstat.itsnik.de
    about: Check our comprehensive documentation
  - name: ğŸ’¡ Feature Requests
    url: https://github.com/Its4Nik/DockStat/discussions/categories/ideas
    about: Share and discuss new feature ideas
  - name: ğŸ†˜ Support
    url: https://github.com/Its4Nik/DockStat/discussions/categories/q-a
    about: Get help from the community
  - name: ğŸ› Security Issues
    url: https://github.com/Its4Nik/DockStat/security
    about: Report security vulnerabilities privately
