name: "dockstat-dev"
services:
  socket-proxy:
    container_name: socket-proxy-dockstat-dev
    image: lscr.io/linuxserver/socket-proxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    read_only: true
    tmpfs:
      - /run
    ports:
      - 2375:2375
    environment:
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONFIGS=1
      - CONTAINERS=1
      - DISABLE_IPV6=1
      - DISTRIBUTION=1
      - EVENTS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - PLUGINS=1
      - POST=1
      - PROXY_READ_TIMEOUT=240
      - SECRETS=1
      - SERVICES=1
      - SESSION=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VERSION=1
      - VOLUMES=1

  sqlite-web:
    container_name: sqlite-web-dockstat-dev
    image: coleifer/sqlite-web:latest
    restart: on-failure
    ports:
      - 8080:8080
    volumes:
      - ./../apps/api:/data
    environment:
      - SQLITE_DATABASE=dockstat.sqlite

  sqlite-web2:
    container_name: sqlite-web-dockstore-verification-dev
    image: coleifer/sqlite-web:latest
    restart: on-failure
    ports:
      - 8181:8080
    volumes:
      - ./../apps/dockstore-verification:/data
    environment:
      - SQLITE_DATABASE=verification.db

  prometheus:
    container_name: prometheus-dockstat-dev
    restart: on-failure
    image: quay.io/prometheus/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./dockstat-dev.prometheus.yml:/etc/prometheus/prometheus.yml
