name: Lint + Format
on: [push]

permissions:
  contents: write

jobs:
  lint:
    name: Lint All packages and Apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Format
        run: |
          bun ci
          bun run format:all

      - name: Commit changes
        if: always()
        run: |
          git config --global user.name 'DockStat Formatter'
          git config --global user.email 'its4nik@users.noreply.github.com'

          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(ci): lint"
            git push
          else
            echo "No changes to commit"
          fi

          exit 0

      - name: Lint
        run: |
          bun run lint:all:ci
