name: Lint + Format
on: [push]

permissions:
  contents: write

jobs:
  lint:
    name: Lint All packages and Apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          bun ci
          bun run lint:fix:all
      - name: Commit changes
        if: always()
        run: |
          git config --global user.name 'DockStat Linter'
          git config --global user.email 'its4nik@users.noreply.github.com'
          git commit -am "chore(ci): Lint"
          git push || exit 0
